### ISSUE TITLE
Как с помощью прав управлять доступом к определенным действиям на сайте

### ISSUE THREAD

**Issue by mikhailborodin** [thinknetica-django-lab-02/py-dev-user#37]
**Что?**

Права могут быть назначены как одному пользователю, так и целой группе. По-умолчанию существуют права для каждой зарегистрированной модели на создание, изменение или удаления объекта

**Задачи**
1. Создать группу “sellers” у которой будут права на изменение и создание новых записей в разделах товары

**Ресурсы**
* https://docs.djangoproject.com/en/3.1/topics/auth/default/#the-login-required-decorator

**Comment by py-dev-user** [comment]
Close #37
Эта группа была создана в самом начале. Проверка соответствующих прав есть в коде.

class ItemCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'main.add_item'
    model = ItemModel
    fields = '__all__'


class ItemUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'main.change_item'
    model = ItemModel
    fields = '__all__'
